listen = { http = "127.0.0.1:8080", socks5 = "127.0.0.1:1080" }
proxy = { http = "127.0.0.1:18080", socks5 = "127.0.0.1:11080" }
mmdb = "Country.mmdb"

[[rules]]
type = "IpNet"
ipnet = "127.0.0.0/8"
rule = "Direct"

[[rules]]
type = "IpNet"
ipnet = "10.0.0.0/8"
rule = "Direct"

[[rules]]
type = "DomainKeyword"
keyword = "icloud"
rule = "Direct"

[[rules]]
type = "DomainKeyword"
keyword = "apple"
rule = "Direct"

[[rules]]
type = "GeoIp"
country = "CN"
rule = "Direct"

[[rules]]
type = "Direct"
rule = "Proxy"
