listen = { http = "127.0.0.1:8080", socks5 = "127.0.0.1:1080" }
proxy = { http = "127.0.0.1:18080", socks5 = "127.0.0.1:11080" }
dns = { listen = "127.0.0.1:55353", upstream_direct = "system", upstream_proxy = "8.8.8.8:53" }

# optional: hosts files, same format as /etc/hosts
# hosts_ipv4 = "config/hosts4.txt"
# hosts_ipv6 = "config/hosts6.txt"

# suffix_domains.txt:
# ```
# cn
# example.com
# ```
#
# domain_sets = [
#     { name = "default", file = "suffix_domains.txt" }
# ]

# mmdb_sets = [
#     { name = "default", file = "Country.mmdb" }
# ]

# optional: the global mmdb file
# mmdb = "Country.mmdb"

rules = [
    { type = "IpNet", ipnet = "127.0.0.0/8", rule = "Direct" },
    { type = "IpNet", ipnet = "10.0.0.0/8", rule = "Direct" },
    { type = "DomainKeyword", keyword = "apple", rule = "Direct" },
    { type = "DomainKeyword", keyword = "icloud", rule = "Direct" },

    # use the suffix domain file associated with the name `default` in domain_sets
    # { type = "DomainSuffixSet", name = "default", rule = "Proxy" },
    # use the suffix_domains.txt file directly
    # { type = "DomainSuffixSet", file = "suffix_domains.txt", rule = "Proxy" },

    # use the global mmdb file
    # { type = "GeoIp", country = "CN", rule = "Direct" },
    # use the mmdb file associated with the name `default` in mmdb_sets
    # { type = "GeoIp", name = "default", country = "CN", rule = "Direct" },

    { type = "Direct", rule = "Proxy" }
]
